api_platform:
    mapping:
        paths: ['%kernel.project_dir%/src/Entity']
    formats:
        json: ['application/json']
        jsonld: ['application/ld+json']
    docs_formats:
        jsonld: ['application/ld+json']
        jsonapi: ['application/vnd.api+json']
    patch_formats:
        json: ['application/merge-patch+json']
    swagger:
        versions: [3]