nelmio_cors:
    defaults:
        origin_regex: true
        allow_credentials: true
        allow_origin: ['http://homecook.wip', 'https://homecook.wip', 'https://api.homecook.wip']
        allow_methods: ['GET', 'OPTIONS', 'POST', 'PUT', 'PATCH', 'DELETE']
        allow_headers: ['Content-Type', 'Authorization']
        expose_headers: ['Link']
        max_age: 3600
    paths:
        '^/api/':
            allow_origin: ['http://homecook.wip', 'https://homecook.wip', 'https://api.homecook.wip']
            allow_credentials: true
            allow_headers: ['Content-Type', 'Authorization', 'X-Requested-With', 'Accept']
            allow_methods: ['POST', 'PUT', 'GET', 'DELETE', 'OPTIONS', 'PATCH']
            max_age: 3600